#!/usr/bin/python

import abcsysbio
import sys

def printOptions():
    print "\n######################## abc-sysbio-sbml-sum"
    print "List of possible options:"
    print "--help\t this description"
    print "--files\t a comma-separated list of xml model files"
    print "--modelset\t a comma-separated list of xml model files belonging to one model\n\t\t\t use tag as many times as there are model sets\n\t\t\t use instead of --files\n\t\t\t order of submodels within model set corresponds to the order of data files"    
    print "--data\t data files with columns <time> <variable1> <variables2> <variable3> ...."
    print "--input_file_name\t the name of the xml file to write (default input_file_template.xml)"
    print "--summary_file_name\t the name of the summary file to write (default model_summary.txt)"
    print "########################\n"

def main():

    if len(sys.argv) == 1:
        printOptions()
        sys.exit()

    input_files = []
    data = None
    filename="input_file_template.xml"
    sumname="model_summary.txt"
    files = False 
    modelset = False 
    length = 1 
    
    for i in range(1,len(sys.argv)):

        if sys.argv[i].startswith('--'):
            option = sys.argv[i][2:]
          
            if option == 'help':
                printOptions()
                sys.exit()
            elif option == 'files':
                tmp=sys.argv[i+1]
                input_files = str(tmp).split(',')
                files = True 
            elif option == 'modelset': 
                tmp=sys.argv[i+1] 
                input_files.extend(str(tmp).split(',')) 
                modelset = True 
                length = len(str(tmp).split(','))
            elif option == 'data': 
                tmp=sys.argv[i+1] 
                data = str(tmp).split(',') 
            elif option == 'input_file_name':
                filename=sys.argv[i+1]
            elif option == 'summary_file_name':
                sumname=sys.argv[i+1] 
            else:
                print "Option --", option, "not recognised"
                sys.exit()

    print "input_files:", input_files 
    print "data:", data
    print "filename:", filename
    print "sumname:", sumname

    if len(input_files) == 0:
        print "No model files have been specified. Exiting."
        sys.exit()
        
    if files == True and modelset == True:     
        print "\n***Entered both 'files' and 'modelset(s)'." 
        printOptions() 
        sys.exit() 

    if data != None: 
        if len(data) != length: 
            print "The number of submodels in each model does not match the number of data sets provided." 
            printOptions() 
            sys.exit() 

    abcsysbio.generateTemplate(input_files, filename=filename, sumname=sumname, length=length, dataname=data)

main()
