#!/usr/bin/python

import abcsysbio
import sys


def main():
    
    source=[]
    for i in range(1,len(sys.argv)):
        source.append(sys.argv[i])

    abcsysbio.generateTemplate(source)

main()
